### ISSUE TITLE
When using the leptos-use with feature 'ssr', the compilation cannot be passed. 

### ISSUE THREAD

**Issue by tqq1994516** [Rust-WASM-WASI/spin_leptos_ssr_starter#6]
For more details, you can take a look at this issue.https://github.com/fermyon/leptos-spin/issues/45

**Comment by benwis** [comment]
@tqq1994516 @itowlson Noting here that the spin_sdk is still on 2. Do you recommend updating to 3?

**Comment by itowlson** [comment]
@benwis The `spin-sdk` needs to match the dependencies of `leptos` and `leptos-spin` (because major versions of `spin-sdk` cannot currently exist in a build).  I'm not sure when `leptos` switched from v2 to v3, although it was on v3 by 0.6.9.  `leptos-spin` 0.1 was on v2 and 0.2 is on v3.

So yeah it would probably be good to bump the leptos, leptos-spin, and spin-sdk dependencies in this repo, but they all have to be done at once I'm afraid.

**Comment by tqq1994516** [comment]
The problem doesn't seem to exist now that `leptos-wasi` has been used. I'm closing this issue.
